/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latian2;

/**
 *
 * @author Rio Aulia Yahya
 */
public class Latian2 extends javax.swing.JFrame {

    /**
     * Creates new form Latian2
     */
    public Latian2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Nama1 = new javax.swing.JLabel();
        Nama2 = new javax.swing.JLabel();
        Nama3 = new javax.swing.JLabel();
        InputAlamat = new javax.swing.JTextField();
        InputNama = new javax.swing.JTextField();
        InputAbsen = new javax.swing.JTextField();
        InputKelas = new javax.swing.JTextField();
        OKE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Formulir");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(168, 11, 38, 14);

        Nama.setText("Alamat");
        getContentPane().add(Nama);
        Nama.setBounds(10, 150, 50, 20);

        Nama1.setText("Nama");
        getContentPane().add(Nama1);
        Nama1.setBounds(10, 36, 50, 20);

        Nama2.setText("Absen");
        getContentPane().add(Nama2);
        Nama2.setBounds(10, 70, 50, 20);

        Nama3.setText("Kelas");
        getContentPane().add(Nama3);
        Nama3.setBounds(10, 110, 50, 20);

        InputAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(InputAlamat);
        InputAlamat.setBounds(60, 150, 120, 30);

        InputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNamaActionPerformed(evt);
            }
        });
        getContentPane().add(InputNama);
        InputNama.setBounds(60, 30, 120, 30);

        InputAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAbsenActionPerformed(evt);
            }
        });
        getContentPane().add(InputAbsen);
        InputAbsen.setBounds(60, 70, 120, 30);

        InputKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputKelasActionPerformed(evt);
            }
        });
        getContentPane().add(InputKelas);
        InputKelas.setBounds(60, 110, 120, 30);

        OKE.setText("OKE");
        OKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKEActionPerformed(evt);
            }
        });
        getContentPane().add(OKE);
        OKE.setBounds(220, 130, 53, 30);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 190, 270, 96);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InputAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAlamatActionPerformed

    private void InputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNamaActionPerformed

    private void InputAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAbsenActionPerformed

    private void InputKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputKelasActionPerformed

    private void OKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKEActionPerformed
        // TODO add your handling code here:
        String nama = InputNama.getText();
        String absen= InputAbsen.getText();
        String kelas = InputKelas.getText();
        String alamat= InputAlamat.getText();
        
        TA.setText("Nama siswa :"+nama+"\n"+"Absen :"+absen+"\n"+"Kelas :"+kelas+"\n"+"Alamat :"+alamat);
    }//GEN-LAST:event_OKEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latian2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latian2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputAbsen;
    private javax.swing.JTextField InputAlamat;
    private javax.swing.JTextField InputKelas;
    private javax.swing.JTextField InputNama;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nama1;
    private javax.swing.JLabel Nama2;
    private javax.swing.JLabel Nama3;
    private javax.swing.JButton OKE;
    private javax.swing.JTextArea TA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
